[build]
  command = "npm run build || echo 'no build step'"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["openapi.yaml"]  # ถ้าใช้ Swagger

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200
